### ISSUE TITLE
Attaching plugin on sub-state triggers on all state updates

### ISSUE THREAD

**Issue by magne4000** [avkonst/hookstate#131]
Given the following state:
```ts
const state: State<{
  a: {
    b: 1
  },
  c: 2
}> = ...;
```

If I attach any plugin to sub-state `b` like this `state.b.attach(MyPuglin)`, all callback methods like `onSet` will be triggered even if I update `c` with `state.c.set(...)`.

I would have expected the plugin to be attached to the substate, on not the whole state.

Use case:
A custom RxJS Observable like [BehaviorSubject](https://rxjs.dev/api/index/class/BehaviorSubject) where I can listen for changes of only a part of my state.

**Comment by avkonst** [comment]
Hi, all plugins except `Downgraded` (which is very special core plugin) are attached per state. This is by design. Tracking plugins for subnested states would make all operations very inefficient. However, you can achieve what you need very easily. `onSet` callback receives an argument `path`, which tells you what state or substate is updated. You can use this to filter out the required events.

**Comment by magne4000** [comment]
Thank you. Indeed, I figured out that I can compare `path`, and it works quite simply. Do you think we could document this behaviour in the plugins documentation?

**Comment by avkonst** [comment]
Yes, we could if it is not already documented. I thought there was
something about it. If it is there, could you please contribute the
proposed change and I will merge. ?
