### ISSUE TITLE
.get() doesn't give me the raw object/array

### ISSUE THREAD

**Issue by lacsinagramar** [avkonst/hookstate#136]
Hi, is there any way I could get the raw object/array from a state?

Here's an example of my code and what I get when I use the .get() function

```javascript
import { createState, useState } from '@hookstate/core'
const defaultGlobalState = createState({
  objectValue: {
    test: 1
  },
  stringValue: 'hello',
  arrayValue: ['first', 'second'],
  integerValue: 1
})

export const Sample = () => {
  const { objectValue, stringValue, arrayValue, integerValue } = useState(defaultGlobalState)

  console.log(objectValue.get()) // Proxy {test: 1}
  console.log(stringValue.get()) // 'hello'
  console.log(arrayValue.get()) // Proxy {0: 'first', 1: 'second'}
  console.log(integerValue.get()) // 1

  return globalState
}

```

**Comment by avkonst** [comment]
Use this to get the original unwrapped object:
`objectValue.attach(Downgraded).get()`

**Comment by lacsinagramar** [comment]
Works like a

> Use this to get the original unwrapped object:
> `objectValue.attach(Downgraded).get()`

Works like a charm ❤️

**Comment by avkonst** [comment]
Keep it open as a reference to update docs

**Comment by onurbamaro** [comment]
> Use this to get the original unwrapped object:
> `objectValue.attach(Downgraded).get()`

This also helped me after hours trying to figure out what was wrong with my code. 

I had a map inside a map and when I tried to unmount the parent .map the child was throwing "cannot read X of undefined"

Applying .attach(Downgraded) on the parent one fixed it. 

Ah, and don't forget to import {Downgraded} from "@hookstate/core"

**Comment by avkonst** [comment]
Would you be able to post here a reproducer for the problem: "when I tried to unmount the parent .map the child was throwing "cannot read X of undefined""?
The proxied object returned by get should have the same behaviour as the original object. But the state object should include only JS types: https://hookstate.js.org/docs/nested-state/#limitations-for-state-values

**Comment by avkonst** [comment]
This is close, but not enough info. The error: "cannot read order of undefined" means some object is undefined whose property `order` you are attempting to access. Unfortunately I can not see where it happens in your example. I am keen to fix it as I believe you should not get the error you are getting, but I can only help if you submit a reproducer. Would you be able to create a repo with a short reproducer which I could clone and run?

**Comment by onurbamaro** [comment]
I tried to create a repo, but I was not able to reproduce myself, crazy... I created the same state object and tried to simulate using variables and it worked as expected. With my actual development environtment I also tried with variables and worked, but when I get back using data from API (which is the same structure) it throws the error. 

Since I was not able to create a repo with the reproducible error I took a screenshot and tomorrow I'll try to create it again

![Error](https://user-images.githubusercontent.com/41651403/113247161-d1ef5100-9290-11eb-9c19-11e92e12b12f.png)

**Comment by avkonst** [comment]
What is the callstack for this error?

**Comment by onurbamaro** [comment]
Now I get it. The problem is that the data coming from the API is not a JS type... I just tested that. Don't know exatcly why, but I'll dig into it. I'm using prisma/graphql-request to fetch data from my api using graphql, maybe something with this library.

In the end, the problem was not Hookstate

**Comment by avkonst** [comment]
Yes, their data is not a JS object, it wrapped by their proxy, not sure
why. I believe there is a method to extract pure object from the fetched
results.

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/issues/238
