### ISSUE TITLE
How to properly prepend value to an array

### ISSUE THREAD

**Issue by magne4000** [avkonst/hookstate#139]
I would like to be able to [unshift](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/unshift) data to an array, is there a way to efficiently do that?
Likewise, is there a way to insert an item at a specific index into an array?

**Comment by avkonst** [comment]
Hi, you can set array value as any other value using `set` function.

I have added the following to the documentation. This will get published online as soon as built.

### Splicing elements

Use `Array.prototype.splice` function to remove, replace or delete elements. In particular, this can be used to prepend new elements to an array value:

```tsx
const state = useState([3000, 4000])
state.set(p => {
    p.splice(0, 0, 1000, 2000);
    return p;
})
```

**Comment by avkonst** [comment]
Does it answer you question?

**Comment by magne4000** [comment]
Is using `splice` like this as efficient as using `merge` to append to an array? I have a use case where I need to quite often insert an item at the beginning, or somewhere in the middle, of an array of possibly more than 10000 items, so I must ensure that this does not trigger unnecessary rendering

**Comment by avkonst** [comment]
splice is done inside of the set, so it will mark the entire array as updated. The problem with optimisation of rendering of arrays is in React itself. Have a look at this component:

```tsx
function MyComponent() {
    let state = useState([1, 2, 3]);
    return <>
    {
        state.keys.map(i => <p key={i}>{i} - {state.value[i]}</p>)
    }
    </>
}
```
When ever an array is modified (appended, prepended, or inserted in the middle), the keys will change and it will require the react to rerender this component. There is no way around optimizing keys due to limitations in React.
Unless you have got different setup of a component dealing with array, I am afraid there is no way to avoid rerendering. If your component looks differently, please share, otherwise I am not able to progress the issue further.

Regarding broadcast plugin - it sends only updated parts. If you update array element, it will only send that element. If you set or merge the entire array, it will send the entire array. I agree this could be improved with the concept of Immer patches. More on this in your other ticket.

**Comment by vangelov** [comment]
Is it possible to prepend a value to an array without marking the entire array as updated? Basically doing the same thing merge() is doing but pre-appending, not appending.

**Comment by avkonst** [comment]
Currently not possible

**Comment by LoganDark** [comment]
When prepending a new value to an array, the indices of all the existing elements change. It's technically possible to avoid rerendering components whose elements haven't changed by specifying a `key` on them that depends on the element itself rather than its position in the list (e.g. if elements have UUIDs). But it's currently not possible for `hookstate` to not mark every element as changed because it thinks all elements have been changed into their previous siblings.

**Comment by avkonst** [comment]
The current behavior of hookstate in case of Array prepend is exactly the same as React useState for array. It might be possible to develop a mechanism to trick the React somehow to do less rerendering, but I have not explored it. The current approach is to rerender each element (perhaps with memo) and rely on react not to change the dom for not changed keys of react components.

**Comment by LoganDark** [comment]
> The current behavior of hookstate in case of Array prepend is exactly the same as React useState for array. It might be possible to develop a mechanism to trick the React somehow to do less rerendering, but I have not explored it. The current approach is to rerender each element (perhaps with memo) and rely on react not to change the dom for not changed keys of react components.

`useState` checks only whole object identity and does no deep comparison whatsoever, so isn't analogous whatsoever.

**Comment by avkonst** [comment]
"useState checks only whole object identity" - yes... and that is exactly what I said above: the hookstate does only that too for array prepend case.

**Comment by LoganDark** [comment]
> "useState checks only whole object identity" - yes... and that is exactly what I said above: the hookstate does only that too for array prepend case.

Hookstate allows you to bind components to individual subfields or sub-subfields of a state. It's responsible for more than just the top level. So I don't think it's equivalent. The sub-subfields think that they've transformed into those of the previous element rather than staying attached to the object that's moved. Non-Hookstate field accesses don't have this problem, because they're compared to those of the last render of the component *with that key*, even if the entire keyed component moves positions in the list. But if you try to pull the same stunt with a component that uses Hookstate:

- `useHookstate` raises exception because the same element now has a different path. You're not allowed to change which State is provided to the hook after the first render.
- Even if that was allowed, all components still need to render again because the prop equality comparisons fail based on the path discrepancy.

**Comment by avkonst** [comment]
"useHookstate raises exception because the same element now has a different path. You're not allowed to change which State is provided to the hook after the first render." - if you have this problem it likely means you are not using they key property for an array element component.

**Comment by LoganDark** [comment]
> "useHookstate raises exception because the same element now has a different path. You're not allowed to change which State is provided to the hook after the first render." - if you have this problem it likely means you are not using they key property for an array element component.

On the contrary it means that you're using a key that doesn't correspond to the array index. In other words it makes prepending an element efficiently impossible because even if you try to pass the correct props to child components, Hookstate won't let you.

**Comment by avkonst** [comment]
Do you see this problem with this approach
https://hookstate.js.org/docs/nested-state/#splicing-elements? Could you
please submit a reproducer?

**Comment by LoganDark** [comment]
> Could you please submit a reproducer?

https://codesandbox.io/p/sandbox/nice-shannon-q5mrsg

It turns out `useHookstate` does not raise the exception I thought it would. Regardless, you can see extra rerenders cause by shifting and unshifting. The swap method you pointed out does have better performance if you do not care about the order at all, but I would say in most situations you probably do care about the order if you are displaying UI about it.
