### ISSUE TITLE
Allow clients to mark certain classes for automatic Downgraded value get

### ISSUE THREAD

**Issue by onattech** [avkonst/hookstate#198]
Hi,
Thank you for the great library. I would like to make sure the way I consume objects is the best practice. So it seems like .get() method can't be used on objects so I am using .attach(Downgraded) to make it work. Is it correct?

```
import "./styles.css";
import {useState, Downgraded} from '@hookstate/core'

export default function App() {
  const myDate = useState(new Date())

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <span>{myDate.get().toISOString()}</span>                       {/* <== failing */}
      <span>{myDate.attach(Downgraded).get().toISOString()}</span>    {/* <== working */}
      <h2>Edit to see some magic happen!</h2>
    </div>
  );
}

```
https://codesandbox.io/s/tender-colden-y4x8x?file=/src/App.js

**Comment by avkonst** [comment]
There is a limitation for what a state value can be: https://hookstate.js.org/docs/nested-state/#limitations-for-state-values
However, you can use it the way you are using. It is fine and will work. I even thought about doing auto-attach of Downgraded for some common types like Date, but there are just to many of them to maintain a list and make it efficient on `get` op... Maybe, it is reasonable to allow a client to mark globally certain types for auto-attach of Downgraded, but not sure...

**Comment by lokutech** [comment]
Thank you for your response and pointing me to https://hookstate.js.org/docs/nested-state/#limitations-for-state-values. I overlooked when I went through the documentation. Having common types like Date getting Downgraded sounds good but it wouldn't solve my issue since I have other objects in my projects. I only gave the date example to make my question simple. I guess .attach(Downgraded) is the solution for me. What is the harm on having Downgraded behavior on all objects by default?

**Comment by avkonst** [comment]
Downgraded opts you out from state usage tracking and it impacts the performance: https://hookstate.js.org/docs/performance-intro
However, if your objects are meant to be consumed in full, it is not an issue for you

**Comment by lokutech** [comment]
Thank you.

**Comment by avkonst** [comment]
I will keep this ticket as a feature request.

**Comment by avkonst** [comment]
related https://github.com/avkonst/hookstate/issues/106
