### ISSUE TITLE
Question: Why is console.log not logging the value but the proxy

### ISSUE THREAD

**Issue by doncuomo** [avkonst/hookstate#246]
Hi,

I do not understand what is happening here and I hope you guys can shed some light on this behaviour.

Setting up a local state:

```
const carState = useState(() => {
  const cars = ["bmw", "audi", "volvo"];

  console.log(cars);

  return {
    cars,
  };
});
```

Log returns: ["bmw", "audi", "volvo"];

What I do not understand is the following:

`console.log(carState.cars.value);`
Proxy: \<target>: Array(3) [ "bmw", "audi", "volvo" ]

`console.log(carState.cars.value.includes("bmw"));`
True

If includes works, why does console.log not return the actual array instead of the proxy?
I was fooling myself that my code was not working lol.

**Comment by malte94** [comment]
I think you need to return "cars.value" or "cars.get()"

**Comment by doncuomo** [comment]
? I'm not sure I understand what you mean. Where do I need to return cars.value?

Like I said. It does work when i ask if carState.cars.value.includes("bmw"). But if this is true, I would expect the console.log(carState.cars.value); to return an array, instead of the proxy.

**Comment by malte94** [comment]
```
import {useState as state} from '@hookstate/core';

function App() {

  const cars = state([
    "audi", "bmw", "volvo"
  ]);

  const getCars = () => {
    return cars.value;
  }

  return (
    <>
    {getCars()}
    </>
  );
}
```

**Comment by avkonst** [comment]
Hi, state.value and state.get() return the same thing and it is proxy wrapped value of a state. It is proxy wrapped for the reason to trace how the state is used in order to optimize rerendering automatically. In 99.99% of cases proxy will give you the same outcome as working with direct value. In a few rare cases (usually optimization and interoperability related) you can use `state.attach(Downgraded).value` to get the original value.

**Comment by avkonst** [comment]
also see https://github.com/avkonst/hookstate/issues/238
