### ISSUE TITLE
Support for concurrent features

### ISSUE THREAD

**Issue by vinczemarton** [avkonst/hookstate#252]
With React 18 there will be a huge demand for concurrent feature compatibility.

Will this library support it out of the box or does it require a new release and until then we should opt out of concurrent features?

**Comment by avkonst** [comment]
The current version 3.x does not support it. It will require a new release.

**Comment by avkonst** [comment]
I checked it out a year ago. I remember adding support for this required to snapshot entire state objects (deep clones), which hits performance of any state management lib, but Hookstate in particular because it never does deep clones when state is updated. I checked it now, it is still an experimental feature.

**Comment by avkonst** [comment]
Also when you are referring to concurrent features, which one do you mean exactly?

**Comment by avkonst** [comment]
Just refreshed my knowledge where React team is up to. I think most of the features will work as is without changes from Hookstate. There is only one thing I am not sure about related to the case if a state is update and triggers rerender of 2 or more components. I am not sure how it will all play together. At worst case scenario we might see independent rerenders for each affected component.

**Comment by avkonst** [comment]
Will get addressed in #287
