### ISSUE TITLE
Saving a nested state into persistence seems to store the entire state to persistence

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#271]
i have a global app state containing many nested states. I want to store only one of the nested states into persistence using the persistence plugin. Right now, it looks like its storing the entire state and gives error if the global app state contains complex objects like "Date" objects (outside the nested state object which i am trying to store )

**Comment by stefanoeb** [comment]
Hmm I always had separate states to persist. Any special reason you're nesting all your state in one place like redux?

It throws the error [because it tries to stringify the state object to store in Local/Async storage](https://github.com/avkonst/hookstate/blob/master/plugins/Persistence/src/Persistence.ts#L20). 
Also in general you should avoid storing non-serializable values like functions or classes on hookstate, more things might break such as the devtools in my experience.
You can try copying the [persistence plugin code](https://github.com/avkonst/hookstate/blob/master/plugins/Persistence/src/Persistence.ts) and modifying to your needs, maybe using another type of storage?

**Comment by rimsila** [comment]
@nateshmbhat Your issues might related with this
https://github.com/avkonst/hookstate/issues/268

**Comment by avkonst** [comment]
Alternatively, you can add your onset callback implementation via a plugin
api and implementation the persistence you need.
