### ISSUE TITLE
How to Create Derived States?

### ISSUE THREAD

**Issue by ziongh** [avkonst/hookstate#276]
First of all, congratulations for this great library!

I was trying to create a state that is derived from other states. I could create using **useRef** **useState (from React)** or **useMemo**.

I've created one [codesandbox](https://codesandbox.io/s/zealous-swartz-02yrey?file=/src/states/filteredData.js) with one example of what I'm trying to do.

Basically, the idea is to have:

- one state to hold one large list of something
- one state to hold one object with filters that will apply
- one state to hold one object with the definition of the sorting that will be applied

With these 3 base states, I'd like to create:

- one hook that depends on the large list and the filter state and returns the filtered list
- one hook that depends on the last one (filtered list) and the sorter definition and returns the filtered list sortered.

What I'm looking for is a way to do this the best way possible, so that:

- the sorting and the filtering only happens when needed (because the list is large and the filtering and sorting logic can be quite complex).
- re-renderes happens only when needed
- state updates propagates to the respective components.
  - updates to the filter, sorter or the original list data
- ability to use async state for the list data

Thank you!

**Comment by avkonst** [comment]
Hi, your question is quite wide.

1. yes, you can create 3 states: data, filter definition, sorting definition
2. you can create custom React hooks which use 3 above states and do necessary business logic
3. "re-renderes happens only when needed" - yes, only when state is updated and it is actually used if you use Hookstate states in 1.
4. "state updates propagates to the respective components" not sure what you mean, but I assume your business logic in custom hooks would take care of it?
5. "ability to use async state for the list data" see this it might help https://hookstate.js.org/docs/asynchronous-state
6. "the sorting and the filtering only happens when needed (because the list is large and the filtering and sorting logic can be quite complex)." your are talking here about custom caching layer on top of Hookstate state value. Hookstate does not provide caching as all cache layers are too much application specific. However, you can write a custom plugin which would listen to the changes in the original unfiltered / unsorted list and would populate filtered and sorted states when it is necessary (or in a way your business logic requires). see more https://hookstate.js.org/docs/writing-plugin
