### ISSUE TITLE
Downgraded plugin is not working

### ISSUE THREAD

**Issue by CyanFroste** [avkonst/hookstate#312]
It's returning the proxy still (v4.0.0-rc13)
- check the line number where I'm consoling it

![image](https://user-images.githubusercontent.com/53912961/180480321-5e54ae6c-c24e-47eb-b3fa-b3d8c0b8201b.png)

**Comment by avkonst** [comment]
This is like a proxy from another lib, i.e. original value you set to the state. Anyway, could you please try State.get({ noproxy: true }) instead of downgraded?

**Comment by avkonst** [comment]
Hookstate-4 will deprecated Downgrade plugin, please use `State.get({ noproxy: true })` instead

**Comment by speigg** [comment]
@avkonst why does the value need to be proxied at all? One going from state -> value, I would expect no more tracking or hookstate errors; e.g., why should't I be able to do this:

```
const state = hookstate({test: 1})
state.value.test = 42 // no error
```

**Comment by avkonst** [comment]
It is strange that your comment disappeared from github.
The answers are
> why does the value need to be proxied at all?
because we want to do fine grained tracking of what properties of objects
are used to optimize rerendering. You can opt out from it using get method
with noproxy flag.
Some React components may not want to be aware about State, but just need
to receive readonly properties to render. These readonly properties can be
State values. And the proxy allows to track what and how the object is used
by a component.

**Comment by avkonst** [comment]
And this
> state.value.test = 42 // no error
should be an error if it is still proxied value... if it is not an error
anymore it is a bug
