### ISSUE TITLE
Batch Hookstate V4

### ISSUE THREAD

**Issue by RunRanger** [avkonst/hookstate#313]
Hi Avkonst,

i've just installed v4 into an existing project (not the best idea since there's no migration and chaning log yet😅)
The batch-function for State-Types became deprecated? Are there any alternatives or does it now hand-in-hand with react v18 and automatically create batches?

**Comment by avkonst** [comment]
Hi, migrations guidelines and docs for hookstate 4 will come soon. Batch was deprecated and removed because it was incompatible with some of the new v4 features. Also it became redundant because React does batching natively now. If you used it for batching, just remove it. If you used it in combination with postpone and/or to react on promised state fulfilment, use new State property 'promise' instead of batch.
