### ISSUE TITLE
Bug : Not getting code completion (Types) for setting initial value for the state

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#336]
Here is the image that shows the issue : 

![image](https://user-images.githubusercontent.com/23279926/188130245-f33494a5-c6fe-4f62-a9ae-0afffcd620b9.png)

**Comment by avkonst** [comment]
hmm... you are right... Typescript stopped showing type suggestions... I think it is because it can not decide which overload it needs to choose until the value is provided. I have put a workaround for TS like this, would it be acceptable?
![image](https://user-images.githubusercontent.com/3971413/188298271-8d24aa5a-d418-4bb2-b45e-7d0a5d2814ee.png)

**Comment by nateshmbhat** [comment]
This way seems unusual to me...
Probably will be confusing to others. Is there no way to have it auto detect based on the generic type we give to hookstate function?

**Comment by avkonst** [comment]
I am not sure. I need to ask Typescript team why VSCode is confused in this case.

**Comment by avkonst** [comment]
This is this issue I believe https://github.com/microsoft/TypeScript/issues/26892. I reproduced it outside of hookstate with just 2 overloads for a function.
