### ISSUE TITLE
NextJS SSR Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by tomer-tgp** [avkonst/hookstate#361]
Hi,
Thank you for the awesome library!

I am using Next13 and I have a cookie I am trying to read on a client component and set the global state with that (user) cookie.
But this code is getting the above error
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

**Code:**
```
'use client';
import React, { useEffect } from 'react';
import { hookstate, useHookstate } from '@hookstate/core';

export const globalUserState = hookstate(false);

export default function MyComponent() {
  const userState = useHookstate(globalUserState);
  useEffect(() => {
    const user = getUserCookie();
    if (user) {
      userState.set(() => user);  // <-- THIS LINE CAUSES THE ERROR
    }
  }, []);

...
}
```

**Libs:**
"next": "13.0.5",
"react": "18.2.0",
"@hookstate/core": "^4.0.0-rc21"

**Comment by Devisione** [comment]
i think you need to use https://hookstate.js.org/docs/asynchronous-state

**Comment by avkonst** [comment]
ok. you should have the same problem with `React.useState`. This nextjs complains about the mismatch because it is definitely different, since the browser will have different data in localstorage then the server would have. You need to disable SSR for a particular component or tell nextjs that the mismatch is expected. Google this problem, there is a lot of information online about this. It is not Hookstate problem.
