### ISSUE TITLE
Use with immutable structures (immutable.js)

### ISSUE THREAD

**Issue by aXises** [avkonst/hookstate#49]
Hi, I been trying to implement scoped states with immutable structures, specifically lists from immutable.js. I run into the problem of needing to convert the `StateLink` of the list, to a list of `StateLinks` elements while forwarding to the child components.

My approach was to map elements of the list to StateLinks with something like
```
  const state = useStateLink(
    List([]),
    s => ({
      nested: s.value.map(x => createStateLink(x)),
    })
  );
```
However, I get the StateLink is used incorrectly error.

What's the deal here, should I stick to Arrays or am I going about this the wrong way.

Thanks.

**Comment by avkonst** [comment]
2 things here:

1. I can not comment what error you are getting and why because it is not enough information you provided

2. Unfortunately state management libs, including Hookstate, Redux and others, can store only the data represented in plain JS types like objects, arrays and primitives. Event Map and Set are hard for the libs. However, you can always wrap the state values to immutable containers if you wish. Something along these lines:

```tsx
const state = useStateLink([]) // plain array here
const valueAsImmutableList = List(state.value)
const nestedStatesAsImmutableList = List(state.nested)
```

Hope this helps. Let me know.

**Comment by aXises** [comment]
Hi @avkonst, Thanks for clarifying, helps a lot.

As for the error, I took the Huge Table performance demo, wrapped the source into a `List`, I tried to recreate the demo using a stateMatrix of `Lists` instead of `Arrays` and adding the transform which converted elements in the list to `StateLinks`. Probably don't worry about it, I think it's unrelated to this.

I'm going to stick to `Arrays` and wrap them into immutable contains when needed.

Cheers.
