### ISSUE TITLE
Polyfill for [self].map?

### ISSUE THREAD

**Issue by MainAero** [avkonst/hookstate#79]
Hi, I'm using this exciting library in a create-react-app project. It seems that some polyfills are missing as I'm seeing errors for IE11 and mobile user when using `map`.

Error: `Cannot read property 'map' of undefined`

For instance for env: Chrome Mobile WebView Version:37.0.0 Android Version:5.0.2

Importing following in `index.ts`

```ts
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'core-js/features/number/is-integer';
import '@hookstate/proxy-polyfill';
```

Code:

```ts
import { useState, self, State } from '@hookstate/core';
import LoaderState from '../state/LoaderState';

export default function useLoaderState() {
  const loadingState = useState(LoaderState);

  return loadingState[self].map((state: State<boolean>) => ({
    get loading() {
      return state.get();
    },
    dispatchLoading(val: boolean) {
      state.set(val);
    },
    toggleLoading() {
      state.set((val: boolean) => !val);
    },
  }));
}

```

with `LoaderState`:
```ts
import { createState } from '@hookstate/core';

const LoaderState = createState<boolean>(false);

export default LoaderState;
```

Any suggestions?

**Comment by MainAero** [comment]
Same for `[self].attach`

**Comment by avkonst** [comment]
Do you have 'import self from @hookstate/core' in your code?

**Comment by MainAero** [comment]
Updated code snipped above with all lines.

**Comment by avkonst** [comment]
Yes, I realised that version 2 API has got broken support for IE. It is broken on `typeof key === 'symbol'`, which always returns false in IE. It is fixable, if [self] is made as a string property by opt-in feature. How critical is it for you?

**Comment by MainAero** [comment]
Want to solve it this week as I need browser support. May I can support somehow?

**Comment by avkonst** [comment]
I am busy this week. I will try to have a look into this during an evening
this week. It should not be hard to fix, just need to debug and verify
carefully. Support would be nice. How would you like to support?

**Comment by avkonst** [comment]
Hey. Some good news. I managed to look into this issue. Because there was no way to bypass `[self]` for IE11, I needed to drop it, i.e. support `StateMethods` (like `get`, `set`, etc..) directly on the `State` object without requiring to use `[self]`. This results in quite great improvement for the API, which I did not think would be good initially. But now I see the API is getting better without `[self]`. It means that I will need to release new major version because `[self]` is gone (I have decided not to support both alternatives for code simplicity). So, I need to put some more time to release new major version, upgrade plugins and docs. Hope you can wait few more days, as it will take time,

PS: when you asked about support, did you mean Patreon like contribution?

**Comment by avkonst** [comment]
Dev branch is here: https://github.com/avkonst/hookstate/tree/version-3

**Comment by MainAero** [comment]
Hey, thanks a lot!!! 
Sound great to simplify the API, will wait for the new major version then.
Regarding support: Either direct code contribution or/and Patreon like.

**Comment by avkonst** [comment]
Version 3 has been released with out of the box support for IE11 (So, remove the hookstate proxy polyfill from your code!!!!). Have a look into the updated demo for IE11: https://github.com/avkonst/hookstate/tree/master/docs/demos/ie11

**Comment by MainAero** [comment]
Just upgraded to v3. Thanks a lot
